{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "ProjetoICC.ipynb",
      "provenance": [],
      "authorship_tag": "ABX9TyMDjnzU5yl/J8kwc5KAfhVn",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Amaliamelo/Projeto-ICC1/blob/CodigoTeste/ProjetoICC.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "Y-9WDWH-fHfJ"
      },
      "outputs": [],
      "source": [
        "#include <stdio.h>\n",
        "#include <string.h>\n",
        "#include <time.h>\n",
        "#include <stdlib.h>\n",
        "#include <locale.h>\n",
        "\n",
        "\n",
        "int MenuInicial();\n",
        "int iniciar();\n",
        "int continuar();\n",
        "void sair();\n",
        "int MenuRodadas();\n",
        "int NovaRodada();\n",
        "int Salvar_Sair();\n",
        "\n",
        "//função principal\n",
        "int main (){\n",
        "\n",
        "    //criando tabuleiro\n",
        "    int tabuleiro[8][4], cont=0;\n",
        "    int i,j;\n",
        "    \n",
        "    for(i=0;i<8;i++){\n",
        "        for(j=0;j<4;j++){\n",
        "        \tcont++;\n",
        "            tabuleiro[i][j]=cont;\n",
        "        }\n",
        "     }\n",
        "    /////\n",
        "    setlocale (LC_ALL,\"Portuguese\");\n",
        "\n",
        "    int x = MenuInicial();\n",
        "\n",
        "    if (x==1){\n",
        "    \tiniciar();\n",
        "    \tint op = MenuRodadas();\n",
        "    \tif(op==1){\n",
        "            NovaRodada(tabuleiro);\n",
        "    \t}else{\n",
        "    \t    if(x==2){\n",
        "                Salvar_Sair();\n",
        "            }\n",
        "            else{\n",
        "                sair();\n",
        "            }\n",
        "    \t}\n",
        "\t}\n",
        "\telse{\n",
        "\t\tif(x==2){\n",
        "\t\t\tcontinuar();\n",
        "\t\t}\n",
        "\t\telse{\n",
        "\t\t\tsair();\n",
        "\t\t}\n",
        "\t}\n",
        "    return 0;\n",
        "}\n",
        "\n",
        " //Menu Inicial\n",
        "int MenuInicial(){\n",
        "    /* Funcao Menu, nao recebe valor e retorna a escolha que o jogador realizar\n",
        "    pode ser: iniciar, continuar,sair\n",
        "    */\n",
        "    int EscolhaJogador;\n",
        "    do{\n",
        "        fprintf(stdout,\"1 - Iniciar 2 - Continuar 3 - sair\\n\");\n",
        "        fprintf(stdout,\"Digite sua escolha: \");\n",
        "        scanf(\"%d\", &EscolhaJogador); //armazenando a escolha\n",
        "        if(EscolhaJogador == 1 || EscolhaJogador == 2 || EscolhaJogador == 3)\n",
        "            // se a escolha for correta, retorna ela\n",
        "            return EscolhaJogador;\n",
        "        if(EscolhaJogador < 1 || EscolhaJogador > 3)\n",
        "        // se for incorreta, entra no loop ate ser digitada corretamente\n",
        "        fprintf(stdout,\"Valor incorreto, digite novamente\\n\");\n",
        "        break;\n",
        "\n",
        "    }while(EscolhaJogador != 3);\n",
        "    return 0;\n",
        "}\n",
        "\n",
        "//Função Iniciar\n",
        "int iniciar(){\n",
        "\n",
        "\tchar NomeUsuario[256];\n",
        "\tchar nome_confirmado[256];\n",
        "\tint ConfirmacaoDoNomeUsuario;\n",
        "\tFILE * arq_usuario;\n",
        "\n",
        "\tprintf(\"Seja Bem - Vindo(a)!!! Digite seu nome de usuário: \");\n",
        "    scanf(\"%s\", NomeUsuario);\n",
        "\n",
        "    printf(\"Seu nome de usuario é: %s \", NomeUsuario);\n",
        "    printf(\"\\n Podemos confirmar?! \\n 1 - sim  2 - nao\\n\");\n",
        "    scanf(\"%d\", &ConfirmacaoDoNomeUsuario);\n",
        "\n",
        "   \twhile(ConfirmacaoDoNomeUsuario != 1 && ConfirmacaoDoNomeUsuario != 2){\n",
        "\t \tprintf(\"Valor incorreto, digite novamente\\n\");\n",
        "\t \tscanf(\"%d\", &ConfirmacaoDoNomeUsuario);\n",
        "\t}\n",
        "\n",
        "    FILE *TestandoNomeUsuario;\n",
        "\n",
        "    if(ConfirmacaoDoNomeUsuario==1){\n",
        "            /*\n",
        "                Criacao dos arquivos e vereficação de repetição realizada\n",
        "                parte de arquivos dos usuarios está pronta\n",
        "                falta: Revisionar com os membros do grupo e upar pra main\n",
        "            */\n",
        "            strcat(NomeUsuario,\".txt\");\n",
        "            strcpy(nome_confirmado,NomeUsuario);\n",
        "            TestandoNomeUsuario=fopen(nome_confirmado,\"r\");\n",
        "        if(TestandoNomeUsuario != NULL){\n",
        "            do{\n",
        "             printf(\"Digite outro nome: \");\n",
        "             scanf(\"%s\", NomeUsuario);\n",
        "             strcat(NomeUsuario,\".txt\");\n",
        "             strcpy(nome_confirmado,NomeUsuario);\n",
        "             TestandoNomeUsuario=fopen(nome_confirmado,\"r\");\n",
        "             if(TestandoNomeUsuario== NULL)\n",
        "                break;\n",
        "            }while(TestandoNomeUsuario != NULL);\n",
        "        }\n",
        "        //Criacao do arquivo utilizando o nome do usuario\n",
        "            arq_usuario=fopen(nome_confirmado,\"w+\");\n",
        "\n",
        "\n",
        "            arq_usuario=fopen(nome_confirmado,\"w+\");\n",
        "\n",
        "            if(arq_usuario == NULL){\n",
        "                printf(\"Deu ruim ao abrir o arquivo usuario\\n\");\n",
        "                exit(0);\n",
        "            }\n",
        "\n",
        "    }\n",
        "\telse{\n",
        "\n",
        "\t}\n",
        "\n",
        "    return 0;\n",
        "}\n",
        "\n",
        "int continuar(){\n",
        "    return 0;\n",
        "}\n",
        "\n",
        "void sair(){\n",
        "    exit(0);\n",
        "}\n",
        "\n",
        "//Menu que aparecerá ao final de cada rodade\n",
        "int MenuRodadas(){\n",
        "\n",
        "\tint EscolhaJogador;\n",
        "\n",
        "    do{\n",
        "        fprintf(stdout,\"\\n 1 - Nova Rodada, 2 - Salvar e sair 3 - Sair\\n\");\n",
        "        fprintf(stdout,\"LEMBRE-SE: a opcao 3 nao salvara o seu percurso até aqui \\n\");\n",
        "        fprintf(stdout,\"\\n Digite sua escolha: \");\n",
        "        scanf(\"%d\", &EscolhaJogador); //armazenando a escolha\n",
        "        if(EscolhaJogador == 1 || EscolhaJogador == 2 || EscolhaJogador == 3)\n",
        "            // se a escolha for correta, retorna ela\n",
        "            return EscolhaJogador;\n",
        "        if(EscolhaJogador < 1 || EscolhaJogador > 3)\n",
        "        // se for incorreta, entra no loop ate ser digitada corretamente\n",
        "        fprintf(stdout,\"Valor incorreto, digite novamente\\n\");\n",
        "        break;\n",
        "\n",
        "    }while(EscolhaJogador != 3);\n",
        "\n",
        "    return 0;\n",
        "\n",
        "}\n",
        "\n",
        "\n",
        "//EM ANDAMENTO --- NÃO ESTÁ PRONTO\n",
        "int NovaRodada(int tabuleiro[8][4]){\n",
        "\n",
        "    //pegar semestre, pontuação e rodada\n",
        "\tint dado, semestre = 1 ,pontuacao;\n",
        "\tint situacao;\n",
        "\n",
        "\tsrand(time(NULL));\n",
        "\t\n",
        "\tdado = rand()%4;\n",
        "\t//FAZENDO O DADO NÃO CAIR EM NUMEROS QUE NÃO VÃO EXISTIR\n",
        "\twhile(dado==4){\n",
        "        dado = rand()%4;\n",
        "\t}\n",
        "\t\n",
        "\t//Pesquisando no Arquivo \n",
        "\t\n",
        "\tFILE * ArquivoSituacoes;\n",
        "\n",
        "\n",
        "\tArquivoSituacoes=fopen(\"situacoes.txt\",\"r\");\n",
        "\t\n",
        "\tif(ArquivoSituacoes!=NULL){\n",
        "\t\tchar texto_situacao[300];\n",
        "\t\tchar string;\n",
        "\t\t\n",
        "\t\t//\tPOSIÇÃO DO PERSONAGEM NO TABULEIRO\n",
        "\t\tsituacao=tabuleiro[semestre][dado]; \n",
        "\t\t\n",
        "\t\tsetlocale (LC_ALL,\"Portuguese\");\n",
        "\n",
        "\t\t\n",
        "\t\tint ComparadorIndicador=0; //numero em que sera realizada a comparação com situação\n",
        "\t\t//percorre todo o arquivo\n",
        "\t\twhile((string = fgetc(ArquivoSituacoes)) != EOF){\n",
        "\t\t\n",
        "\n",
        "\t\t\tfscanf(ArquivoSituacoes, \"%d\", &ComparadorIndicador); //procurando o id da situação no arquivo\n",
        "\t\t\t\n",
        "\t\t\tint i = -1;//contador do vetor\n",
        "\t\t\t\n",
        "\t\t\tif(ComparadorIndicador==situacao){///quando id da situação for entrado, faça:\n",
        "\t\t\t\t//situacao++;\n",
        "\t\t\t\t\n",
        "\t\t\t\t//escrevendo situação e suas alternativas, caso haja uma \"|'\n",
        "\t\t\t\tdo{\n",
        "\t\t\t\t\ti++;\n",
        "\t\t\t\t\tfscanf(ArquivoSituacoes, \"%c\", &texto_situacao[i]);\n",
        "\t\t\t\t\tprintf(\"%c\", texto_situacao[i]);\n",
        "\t\t\t\t\t\n",
        "\t\t\t\t}while(texto_situacao[i] != '|' );\n",
        "\t\t\t\t\n",
        "\t\t\t\t\n",
        "\t\t\t\t//lendo pelo tamanho do texto situação\n",
        "\t\t\t\t/*for(i=0;i<256;i++){\n",
        "\t\t\t\t\tfscanf(ArquivoSituacoes, \"%c\", &texto_situacao[i]);\n",
        "\t\t\t\t\tfprintf(stdout, \"%c\", texto_situacao[i]);\n",
        "\t\t\t\t\t\n",
        "\t\t\t\t}*/\n",
        "\t\t\t\n",
        "                 \n",
        "\t\t\t\tbreak;\n",
        "\t\t\t}\n",
        "\n",
        "\t\t}\n",
        "\t\t\n",
        "\t}\n",
        "   \n",
        "}\n",
        "\n",
        "//NÃO TA PRONTO....FALTA ARQUIVO\n",
        "int Salvar_Sair(){\n",
        "    return(0);\n",
        "    printf(\"teste\");\n",
        "}"
      ]
    }
  ]
}
